Repository abigailgeorgia93/Instaclone-fe, pull requests merged in 2024-10, with the labels that each got.

#1 chore: add files
  package-lock.json
  package.json
  src/components/footer/Footer.css
  src/components/footer/Footer.jsx
  src/components/header/Header.css
  src/components/header/Header.jsx
  src/components/layout/Layout.css
  src/components/layout/Layout.jsx
  src/components/logOrSign/LogOrSign.css
  src/components/logOrSign/LogOrSign.jsx
  src/components/logOrSign/login/Login.css
  src/components/logOrSign/login/Login.jsx
  src/components/logOrSign/signup/Signup.css
  src/components/logOrSign/signup/Signup.jsx
  src/pages/imagespage/ImagesPage.jsx
  src/pages/landingpage/LandingPage.jsx
Labels: chore

#2 footer
  src/components/footer/Footer.css
  src/components/footer/Footer.jsx
Labels: enhancement

#3 Header sw
  src/App.jsx
  src/components/header/Header.css
  src/components/header/Header.jsx
Labels: enhancement

#4 Login fe dw
  src/components/logOrSign/LogOrSign.jsx
  src/components/logOrSign/login/Login.jsx
Labels: enhancement

#5 bug-fix: incorrect spellings
  src/components/logOrSign/LogOrSign.jsx
Labels: chore

#6 Signup functionality sw
  src/components/logOrSign/signup/Signup.css
  src/components/logOrSign/signup/Signup.jsx
  src/utils/fetch.js
Labels: enhancement

#8 bug-fix: spell check and import loginFetch
  src/components/logOrSign/LogOrSign.jsx
  src/components/logOrSign/login/Login.jsx
Labels: chore

#9 debugging
  src/App.jsx
  src/components/layout/Layout.css
Labels: bug

#10 bug-fix: screen display working
  src/components/layout/Layout.jsx
  src/main.jsx
Labels: chore

#11 chore: add imageContainer/Card folders & files
  src/components/imageContainer/imageCard/imageCard.css
  src/components/imageContainer/imageCard/imageCard.jsx
  src/components/imageContainer/imageContainer.css
  src/components/imageContainer/imageContainer.jsx
Labels: chore

#12 chore: add general.css file in src & targetted logOrSign styling
  src/components/logOrSign/LogOrSign.css
  src/components/logOrSign/LogOrSign.jsx
  src/components/logOrSign/login/Login.css
  src/general.css
Labels: chore

#13 update header and footer
  src/assets/Instadog.png
  src/components/footer/Footer.css
  src/components/footer/Footer.jsx
  src/components/header/Header.css
  src/components/header/Header.jsx
  src/components/layout/Layout.css
  src/components/layout/Layout.jsx
  src/pages/landingpage/LandingPage.jsx
Labels: enhancement

#15 bug-fix: duplicate code
  src/components/layout/Layout.jsx
Labels: chore

#16 header_and_footer
  package-lock.json
  package.json
  src/assets/home.png
  src/assets/images.png
  src/components/footer/Footer.css
  src/components/header/Header.css
  src/components/header/Header.jsx
  src/components/layout/Layout.css
  src/pages/landingpage/LandingPage.jsx
Labels: chore

#18 bug-fix: import useState and partial fix of body, full size with ove…
  src/App.jsx
  src/components/layout/Layout.css
Labels: chore

#21 chore: fetchupdate
  src/utils/fetch.js
Labels: chore

#22 chore: imagecard
  src/components/imageContainer/imageCard/ImageCard2.jsx
Labels: chore

#24 update styling so writting is visible for user
  src/components/header/Header.css
  src/components/layout/Layout.css
Labels: enhancement

#23 chore: env update
  src/App.jsx
  src/pages/landingpage/LandingPage.jsx
Labels: chore

#25 bug-fix: sign up working on inspector tool
  src/App.jsx
  src/components/logOrSign/signup/Signup.jsx
  src/pages/landingpage/LandingPage.jsx
  src/utils/fetch.js
Labels: bug

#26 added fe functions and styling to centered screen and relative postio…
  src/components/logOrSign/LogOrSign.css
  src/components/logOrSign/LogOrSign.jsx
  src/components/logOrSign/login/Login.css
  src/components/logOrSign/login/Login.jsx
  src/components/logOrSign/signup/Signup.css
  src/index.css
  src/pages/landingpage/LandingPage.css
  src/pages/landingpage/LandingPage.jsx
Labels: enhancement

#27 chore: bugfix on styling
  src/components/imageContainer/imageCard/imageCard.css
  src/components/layout/Layout.css
Labels: bug
